spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://svc.sel3.cloudtype.app:30271/sns
  username: root
  password: root0613
  platform: postgres
  driver-class-name: org.postgresql.Driver

spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

jwt:
  secret-key: minjeong.sns-2023.secret_key.more.more
  token.expired-time-ms: 2592000000 # 24*60*60*30 -> 30?

spring.redis.url: redis://svc.sel3.cloudtype.app:31231

# yml 사용하는 이유: 결합성 줄이기 위해